//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CuadrigaInterfaces
{
    [Serializable]
    public class GPXPathMsg : Message
    {
        public const string k_RosMessageName = "cuadriga_interfaces/GPXPath";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.NavSatFixMsg[] waypoints;

        public GPXPathMsg()
        {
            this.waypoints = new Sensor.NavSatFixMsg[0];
        }

        public GPXPathMsg(Sensor.NavSatFixMsg[] waypoints)
        {
            this.waypoints = waypoints;
        }

        public static GPXPathMsg Deserialize(MessageDeserializer deserializer) => new GPXPathMsg(deserializer);

        private GPXPathMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.waypoints, Sensor.NavSatFixMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.waypoints);
            serializer.Write(this.waypoints);
        }

        public override string ToString()
        {
            return "GPXPathMsg: " +
            "\nwaypoints: " + System.String.Join(", ", waypoints.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
